### PR TITLE
Created a method for adding context menu items from a plugin

### PR DESCRIPTION
**Pull request by Sindarius**
Created a uiinjection state module that is used to register context menu items.

Currently the mechanism is only implemented on the JobFileList.vue but can easily be extended to additional areas.

### CODE REVIEW

**Comment by chrishamm** [comment]
Thanks, a few notes:

1) There is already another interface for component injection in `src/App.vue` and `src/plugins/index.js`. Please use the same interface or move the existing one to the new Vuex store so we can avoid redundancy
2) I don't think there is a need to define both an action and a mutation for `addContextMenuItem`, I believe a mutation + commit call should be sufficient
3) Please don't mix double and single quotes

**Comment by Sindarius** [comment]
#1  This is likely a naming issue. I called it UI Injection but it's not injecting components it's simply registering some data to the store for registering data necessary for adding to a context menu. It could probably use a better name than injection.

For example in the index.js of my plugin I add a call

registerPluginContextMenuItem('View 3D', '/GCodeViewer', 'mdi-rotate-3d', 'view-3d-model', ContextMenuType.JobFileList);

this sets up the store to have the data to render a context menu item and perform an action such as emitting a message and routing to a new page. 

I can fix #2 and #3.

**Comment by chrishamm** [comment]
Well yes, the part I mentioned does inject dynamically loaded components into App.vue, that's why I called it component injection. I think it would be good to have both in the same file.

**Comment by chrishamm** [comment]
Hi, no offense, all good! Just please move my methods from App + plugins to your new uiInjection module and get rid of the action in favor of the single mutation.

**Comment by Sindarius** [comment]
Excellent,
No offense was taken :) Looking forward to the 3.2 release to push out some exciting plugins.

**Comment by Sindarius** [comment]
Made your recommended changes and made sure there were no issues with the On Screen Keyboard plugin after making the move.

**Comment by chrishamm** [comment]
Thanks, I've merged your changes but refactored parts of it in another commit. Note that I've moved your new context menu functions to plugins/index.js so you'll have to change the import in your G-code viewer plugin.

**Pull request merged**
