### PR TITLE
Add two options - decimalPlaces and displayUnits

### PR DESCRIPTION
**Pull request by MZachmann**
decimalPlaces determines how many decimal places are shown in the dashboard coordinate display

displayUnits determines what unit of measure (inch/mm) is used for those coordinates as well as what units are used for the speeds (mm/s or ipm)

these only affect displayed values

### CODE REVIEW

**Comment by chrishamm** [comment]
It doesn't make sense to display more than three decimal places because
reprapfirmware does not report a higher precision.

Mark Zachmann ***@***.***> schrieb am Fr., 8. Apr. 2022,
18:30:

**Comment by MZachmann** [comment]
ok. are you sure that's true in inches?

**Comment by chrishamm** [comment]
I am sure about mm because that's what is reported to and displayed on Dwc.

**Comment by MZachmann** [comment]
I'm trying to add both inch display support and selectable decimal places. Since the options are closely linked in the structure I just did a pull for both changes. 

I started from needing 2 decimal places (for mm), then wanting it in inches, then needing 3 decimal places and thinking about 4 for rare tests. Having imperial is a huge convenience when working in the US and this code change is so benign.

**Comment by chrishamm** [comment]
Thanks, I'll have a look!

**Pull request merged**
