### PR TITLE
Make dwc friendlier to reverse proxying

### PR DESCRIPTION
**Pull request by pfn**
Small fix to several locations that were not properly honoring `BASE_URL` to fix reverse proxy support

### CODE REVIEW

**Comment by pfn** [comment]
Hmm, looks like this was already fixed in 3.3-dev?

**Comment by chrishamm** [comment]
That's possible, I reworked the AJAX path assembly in v3.3 (and backported it to 3.2 AFAIR) to fix an issue that could occurr when DWC attempted to reconnect. If further configuration steps are required with your changes to enable reverse-proxies, please update the README file as well and I'll merge your PR.

**Comment by pfn** [comment]
@chrishamm I rebased on 3.3-dev, took a look, and applied a few small changes to make reverse proxying work in my configuration.

**Comment by pfn** [comment]
Hi @chrishamm, I've been testing this out and it's working well for me, it's ready to merge if you don't have any concerns.

**Comment by chrishamm** [comment]
Thanks!

**Pull request merged**
