### PR TITLE
Implement thumbnails on file list

### PR DESCRIPTION
**Pull request by Sindarius**
This pull request implements thumbnails in the file list as well as providing a click on the thumbnail to pull up the last image on the list. The thumbnail column is hidden until a thumbnail is loaded.

### CODE REVIEW

**Comment by Sindarius** [comment]
Directory with thumbnails
image

Directory without thumbnails in it
image

Image Preview   click on thumbnail to show and click again to dismiss
image

**Comment by smoki3** [comment]
Would be cool to have an option to turn it on and off

**Comment by bttguy** [comment]
Cant wait this feature :)

**Comment by bttguy** [comment]
Any plan/chance to add this feature to the upcoming v3.3 ? :)

**Comment by bttguy** [comment]
Good tho hear that! @Sindarius Would you implement the required changes so that your already done work would be a very nice addition to DWC? 🙂

**Comment by bttguy** [comment]
Any update on this PR?  Any chance that you can complete it, if the original dev abandoned the project? :)

**Comment by chrishamm** [comment]
The required API calls to extract thumbnails from G-codes in standalone mode haven't been implemented in v3.3 RC so this PR won't make it into DWC before v3.4.

**Comment by bttguy** [comment]
Can we expect/aks this feature to be implemented in the upcoming 3.4? It would be a really nice touch :)

**Comment by chrishamm** [comment]
@bttguy Yes I think so, but I'd like to have thumbnail support implemented in the firmware (standalone mode) before I accept this PR.

**Comment by bttguy** [comment]
@chrishamm How is this feature progressing? :) Will it make into 3.4?

**Comment by P-C-R** [comment]
@chrishamm +1

**Comment by xPew** [comment]
Hi @chrishamm! I read the discussion on this one. How's the implementation goes? Will it make it? :)

**Comment by chrishamm** [comment]
Thumbnail support will come in 3.4-rc1.

**Pull request closed without merging**
